package com.infosaj.saj60

object Data{
    val usfs = listOf(
        UsfContructor(
            img = 0,
            id = R.id.usfAlMo,
            usfName = "USF Alto do Morro",
            aten = "Segunda à Sexta, das 8h às 17h",
            addr = "POVOADO ALTO DO MORRO S/N ZONA RURAL\n" +
                    "CEP: 44435428 - Alto do Morro - Santo Antônio de Jesus - BA",
            phone = "(75) 3632-4482",
            serv = "A Unidade possui farmácia, realiza a vigilância sanitária e faz acompanhamento de pré-natal de risco habitual.",
            team = "É composta  por agentes comunitários de saúde, técnicos em enfermagem, enfermeiros, auxiliar em saúde bucal, médicos e cirurgião dentista."),
        UsfContructor(
            img = 0,
            id = R.id.usfASA,
            usfName = "USF ALTO SANTO ANTÔNIO",
            aten = "Segunda à Sexta, das 8h às 17h",
            addr = "Rua 12, S/N. CEP: 44435428, Bairro Alto Santo Antônio, Santo Antônio de Jesus.",
            phone = "(75) 3631-5654",
            serv = "A unidade realiza acompanhamento de pré-natal de risco habitual, possui farmácia, monitora diagnósticos e tratamentos e atua sobre a vigilância epidemiológica.",
            team = "É composta por agentes comunitários de saúde, técnicos em enfermagem, enfermeiros, auxiliar em saúde bucal, cirurgião dentista e médicos."),
        UsfContructor(
            img = 0,
            id = R.id.usfASIeII,
            usfName = "USF ALTO SOBRADINHO I e II",
            aten = "Segunda à Sexta, das 8h às 17h",
            addr = "",
            phone = "não disponibilizam",
            serv = "A Unidade conta com monitor de pressão não invasivo e reanimador pulmonar/ambu, que tem função de reoxigenar o paciente, caso precise. Também é realizado o acompanhamento do pré-natal de risco habitual e possui farmácia.",
            team = "É composta por agentes comunitários de saúde, técnicos de enfermagem, enfermeiros, médicos, cirurgião dentista e auxiliar de saúde bucal."),
        UsfContructor(
            img = 0,
            id = R.id.usfAnd,
            usfName = "USF DO ANDAIÁ",
            aten = "Segunda à Sexta, das 8h às 17h",
            addr = "Rua Teodoro Dias Barreto, n° 799. CEP: 44435428 - Andaia - Santo Antônio de Jesus - BA",
            phone = "(75) 3631-4689",
            serv = "A unidade realiza acompanhamento de pré-natal de risco habitual, possui farmácia acomoanha diagnósticos e tratamentos, realiza vigilância epidemiológica do local e oferece atendimento psicossocial.",
            team = "É composta por agentes comunitários de saúde, técnicos em enfermagem, enfermeiros médico, auxiliar em saúde bucal e cirurgião dentista. "),
        UsfContructor(
            img = 0,
            id = R.id.usfAmp,
            usfName = "USF DO AMPARO",
            aten = "Segunda à Sexta, das 8h às 17h",
            addr = "Av. Vereador João Silva, s/n, CEP 44436174, Bairro Amparo.",
            phone = "Não disponibilizado ",
            serv = "A unidade realiza acompanhamento de pré-natal de risco habitual, possui farmácia e atua com a saúde da família.",
            team = "É composta por  agentes comunitários de saúde, técnicos em enfermagem, enfermeiros, auxiliar em saúde bucal, cirurgião dentista e médicos."),
        UsfContructor(
            img = 0,
            id = R.id.usfAPDR,
            usfName = "USF AURELINO PEREIRA DOS REIS",
            aten = "Segunda à Sexta, das 8h às 17h",
            addr = "Rua Marieta Martins 101. CEP: 44573250 -  Bairro Radio Clube - Santo Antônio de Jesus - BA",
            phone = "(75) 3632-4751",
            serv = "Possui farmácia, realiza diagnóstico e tratamento, faz acompanhamento de pré-natal e realiza vigilância epidemiológica.",
            team = "É composta por agentes comunitários de saúde, técnicos de enfermagem, enfermeiros, médico, cirurgião dentista e auxiliar de saúde bucal."),
        UsfContructor(
            img = 0,
            id = R.id.usfBID,
            usfName = "USF Bairro Irmã Dulce",
            aten = "Segunda à Sexta, das 8h às 17h",
            addr = "Rua Amaral, S/N. CEP: 44572901 - Irmã Dulce",
            phone = "(75) 3631-6659",
            serv = "A unidade realiza acompanhamento de pré-natal de risco habitual, possui farmácia, monitora diagnósticos e tratamentos e atua sobre a vigilância epidemiológica.",
            team = "É composta por agentes comunitários de saúde, técnicos em enfermagem, enfermeiros, auxiliar em saúde bucal, cirurgião dentista, médico e profissional de educação física."),
        UsfContructor(
            img = 0,
            id = R.id.usfBV,
            usfName = "USF BELA VISTA",
            aten = "Segunda à Sexta, das 8h às 17h",
            addr = "RUA BELA VISTA 383, CEP: 44574520 - Cajueiro - Santo Antônio de Jesus - BA",
            phone = "(75) 3632-9632",
            serv = "A Unidade possui farmácia, realiza a vigilância sanitária, faz acompanhamento de pré-natal de risco habitual e faz acompanhamento de pessoas com diagnósticos e que precisam de tratamentos.",
            team = "É composta por agentes comunitários de saúde, técnicos em enfermagem, enfermeiros, auxiliar em saúde bucal, cirurgião dentista e médico."),
        UsfContructor(
            img = 0,
            id = R.id.usfBVB,
            usfName = "USF BOA VISTA BOMFIM",
            aten = "Segunda à Sexta, das 8h às 17h",
            addr = "Comunidade do Bomfim, s/n, Zona Rural. CEP 44572901.",
            phone = "(75) 98872-3854",
            serv = "A unidade realiza acompanhamento de pré-natal de risco habitual, possui farmácia, realiza diagnóstico e e acompanha tratamentos e faz a vigilância epidemiológica.",
            team = "É composta por  agentes comunitários de saúde, técnicos em enfermagem, enfermeiros, auxiliar em saúde bucal, cirurgião dentista, médico, fisioterapeuta, farmacêutico, psicólogo, nutricionista"),
        UsfContructor(
            img = 0,
            id = R.id.usfCF,
            usfName = "UBS CASACA DE FERRO",
            aten = "Segunda à Sexta, das 8h às 17h",
            addr = "Fazenda Casaca de Ferro s/n. Zona Rural - Santo Antônio de Jesus",
            phone = "(75) 3632-4482",
            serv = "Possui Farmácia",
            team = "Técnicos em enfermagem"),
        UsfContructor(
            img = 0,
            id = R.id.usfCNII,
            usfName = "UBS CIDADE NOVA II",
            aten = "Segunda à Sexta, das 8h às 17h",
            addr = "",
            phone = "Não disponível",
            serv = "A Unidade possui farmácia e faz acompanhamento do pré-natal de risco habitual. ",
            team = "Cirurgião dentista, auxiliar de saúde bucal, enfermeiro, técnico em enfermagem, médico clínico e agente comunitário de saúde."),
        UsfContructor(
            img = 0,
            id = R.id.usfCUI,
            usfName = "USF DO CALABAR URBIS I",
            aten = "Segunda à Sexta, das 8h às 17h",
            addr = "Rua do Calabar, Urbis I, n° 690, CEP 44435428",
            phone = "Não disponibilizado",
            serv = "A unidade realiza acompanhamento de pré-natal de risco habitual, possui farmácia, realiza diagnóstico e acompanha tratamentos e possui reanimadores pulmonares.",
            team = "É composta por  agentes comunitários de saúde, técnicos em enfermagem, enfermeiros, auxiliar em saúde bucal, cirurgião dentista e médico."),
        UsfContructor(
            img = 0,
            id = R.id.usfFQ,
            usfName = "USF FERNANDO QUEIROZ",
            aten = "Segunda à Sexta, das 8h às 17h",
            addr = "Urbis IV, Caminho 03 CEP: 44574270, Bairro providência.",
            phone = "(75) 3632-4281",
            serv = "A unidade realiza acompanhamento de pré-natal de risco habitual, possui farmácia e faz o controle da vigilância epidemiológica.",
            team = "É composta por  agentes comunitários de saúde, técnicos em enfermagem, enfermeiros, auxiliar em saúde bucal, cirurgião dentista, médicos, assistente social, farmacêutico, fisioterapeuta e nutricionista."),
        UsfContructor(
            img = 0,
            id = R.id.usfGPSII,
            usfName = "USF GERALDO PESSOA SALLES II",
            aten = "Segunda à Sexta, das 8h às 17h",
            addr = "Loteamento Sol Nascente, n° 148 CEP: 44572040 - Barro Vermelho",
            phone = "(75) 3632-4281",
            serv = "A unidade realiza acompanhamento de pré-natal de risco habitual, possui farmácia, realiza diagnóstico e acompanha tratamentos.",
            team = "É composta por  agentes comunitários de saúde, técnicos em enfermagem, enfermeiros, auxiliar em saúde bucal, cirurgião dentista e médicos."),
        UsfContructor(
            img = 0,
            id = R.id.usfMA,
            usfName = "USF MARITA AMÂNCIO",
            aten = "Segunda à Sexta, das 8h às 17h",
            addr =  "RUA NOVA DO CAJUEIRO 65, CEP: 44435428 - Cajueiro - Santo Antônio de Jesus - BA",
            phone = "Não disponibilizado",
            serv = "A Unidade possui farmácia, realiza a vigilância sanitária, acompanha diagnósticos e tratamentos e faz acompanhamento de pré-natal de risco habitual. ",
            team = "É composta  por agentes comunitários de saúde, técnicos em enfermagem, enfermeiros, médicos, cirurgião dentista e auxiliar de saúde bucal."),
        UsfContructor(
            img = 0,
            id = R.id.usfPCMS,
            usfName = "USF DO POVOADO DO COCAO MINAS DO SAPÉ",
            aten = "Segunda à Sexta, das 8h às 17h",
            addr = "Comunidade Minas do Sapé, s/n Zona Rural Cocão - Santo Antônio de Jesus - BA",
            phone = "(75) 98154-5197",
            serv = "A unidade realiza acompanhamento de pré-natal de risco habitual, possui farmácia, equipamentos de raio-x dentário, reanimadores pulmonares e a unidade controla a vigilância epidemiológica.",
            team = "É composta por agentes comunitários de saúde, técnicos em enfermagem, cirurgião dentista, auxiliar de saúde bucal, médico e enfermeiro"),
        UsfContructor(
            img = 0,
            id = R.id.usfSFIeII,
            usfName = "USF SÃO FRANCISCO I E II",
            aten = "Segunda à Sexta, das 8h às 17h",
            addr = "Rua Wellington Figueiredo, n° 72, casa. São Benedito. CEP: 44572901",
            phone = "(75) 3632-4807",
            serv = "A Unidade possui farmácia, realiza a vigilância sanitária, faz acompanhamento de pré-natal de risco habitual e faz acompanhamento de pessoas com diagnósticos e que precisam de tratamentos.",
            team = "É composta por agentes comunitários de saúde, técnicos em enfermagem, enfermeiros, auxiliar em saúde bucal, cirurgião dentista e médicos."),
        UsfContructor(
            img = 0,
            id = R.id.usfSP,
            usfName = "USF SÃO PAULO",
            aten = "Segunda à Sexta, das 8h às 17h",
            addr = "Antiga rua D, complemento: Rua B",
            phone = "(75) 3632-4485",
            serv = " A Unidade possui farmácia, realiza a vigilância sanitária, faz acompanhamento de pré-natal de risco habitual e faz acompanhamento de pessoas com diagnósticos e que precisam de tratamentos.",
            team = "A equipe é composta por agentes comunitários de saúde, técnicos em enfermagem, enfermeiros, auxiliar em saúde bucal, cirurgião dentista, médicos, profissional de educação física e auxiliar de laboratório de análises clínicas. "),
        UsfContructor(
            img = 0,
            id = R.id.usfSM,
            usfName = "USF SANTA MADALENA",
            aten = "Segunda à Sexta, das 8h às 17h",
            addr = "Rua Justiniano Rocha Galvão, n°320, Bairro Santa Madalena.",
            phone = "(75) 3631-5654",
            serv = "A unidade realiza acompanhamento de pré-natal de risco habitual e possui farmácia.",
            team = "É composta por agentes comunitários de saúde, técnicos em enfermagem, enfermeiros e médico."),
        UsfContructor(
            img = 0,
            id = R.id.usfUIII,
            usfName = "USF URBIS III",
            aten = "Segunda à Sexta, das 8h às 17h",
            addr = "Rua A, S/N, Urbis III, cep 44435428, Bairro Santa Terezinha.",
            phone = "(75) 3632-4710 ",
            serv = "A unidade realiza acompanhamento de pré-natal de risco habitual, possui farmácia, monitora diagnósticos e tratamentos e atua sobre a vigilância epidemiológica.",
            team = "É composta por  agentes comunitários de saúde, técnicos em enfermagem, enfermeiros, auxiliar em saúde bucal, cirurgião dentista e médicos."),
        UsfContructor(
            img = 0,
            id = R.id.usfVL,
            usfName = "USF VIRIATO LOBO",
            aten = "Segunda à Sexta, das 8h às 17h",
            addr = "Rua João Mota de Oliveira, sem número, Cajueiro, Santo Antônio de Jesus.",
            phone = "(75) 3631-5654",
            serv = "A Unidade possui farmácia, realiza a vigilância sanitária, realiza atendimento psicossocial, faz acompanhamento de pré-natal de risco habitual e faz acompanhamento de pessoas com diagnósticos e que precisam de tratamentos.",
            team = "É composta por agentes comunitários de saúde, técnicos em enfermagem, enfermeiros, auxiliar em saúde bucal, cirurgião dentista, médicos e profissional de educação física"),
        UsfContructor(
            img = 0,
            id = R.id.usfZA,
            usfName = "UBS ZILDA ARNS",
            aten = "Segunda à Sexta, das 8h às 17h",
            addr = "Avenida Carlos Amaral, s/n, CEP 44571000",
            phone = "Não disponibilizado",
            serv = "A unidade realiza acompanhamento de pré-natal de risco habitual, possui farmácia, realiza diagnóstico e acompanha tratamentos e faz a vigilância epidemiológica.",
            team = "É composta por  agentes comunitários de saúde, técnicos em enfermagem, enfermeiros, auxiliar em saúde bucal, cirurgião dentista e médicos.")
    )
}

val teste = Data.usfs

fun main(){
    println(teste[0])

}
